apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: pkc1310/my-k8s-web-app
      ports:
        - containerPort: 3000
